# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg1c-6ZOyk1cipw3bEWfzcCTA4zMdNNc
"""

# api.py

import io
import torch
import torch.nn as nn
from fastapi import FastAPI, File, UploadFile
from PIL import Image
import torchvision.transforms as transforms

# -------------------------------
# 1. Define Model (same as training)
# -------------------------------
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv_layer = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )

        self.fc_layer = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 4 * 4, 256),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(256, 10)
        )

    def forward(self, x):
        x = self.conv_layer(x)
        x = self.fc_layer(x)
        return x


# -------------------------------
# 2. Load Model
# -------------------------------
device = torch.device("cpu")

model = CNN()
model.load_state_dict(torch.load("cnn_cifar10_weights.pth", map_location=device))
model.to(device)
model.eval()

# CIFAR-10 Classes
classes = ['plane', 'car', 'bird', 'cat', 'deer',
           'dog', 'frog', 'horse', 'ship', 'truck']

# -------------------------------
# 3. Image Preprocessing
# -------------------------------
transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])


def preprocess_image(image: Image.Image):
    image = image.convert("RGB")
    image = transform(image)
    image = image.unsqueeze(0)  # Add batch dimension
    return image


# -------------------------------
# 4. FastAPI App
# -------------------------------
app = FastAPI()

@app.get("/")
def home():
    return {"message": "CIFAR-10 CNN API is running"}

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    contents = await file.read()
    image = Image.open(io.BytesIO(contents))

    input_tensor = preprocess_image(image)
    input_tensor = input_tensor.to(device)

    with torch.no_grad():
        outputs = model(input_tensor)
        _, predicted = torch.max(outputs, 1)

    predicted_class = classes[predicted.item()]

    return {
        "prediction": predicted_class
    }